-- MySQL Script generated by MySQL Workbench
-- Wed May 25 14:16:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clients
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clients` ;

-- -----------------------------------------------------
-- Schema clients
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clients` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clients` ;

-- -----------------------------------------------------
-- Table `clients`.`infopayements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infopayements` (
  `Codepayement` INT NOT NULL AUTO_INCREMENT,
  `DatePayement` DATE NOT NULL,
  `Description` VARCHAR(50) NOT NULL,
  `Montant` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Codepayement`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infoclients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infoclients` (
  `Codeclient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(30) NOT NULL,
  `Prenoms` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `infopayements_Codepayement` INT NOT NULL,
  PRIMARY KEY (`Codeclient`, `infopayements_Codepayement`),
  INDEX `fk_infoclients_infopayements1_idx` (`infopayements_Codepayement` ASC) VISIBLE,
  CONSTRAINT `fk_infoclients_infopayements1`
    FOREIGN KEY (`infopayements_Codepayement`)
    REFERENCES `clients`.`infopayements` (`Codepayement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infocategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infocategories` (
  `Codecategories` INT NOT NULL AUTO_INCREMENT,
  `Action` VARCHAR(45) NOT NULL,
  `Comedie` VARCHAR(45) NOT NULL,
  `Aventure` VARCHAR(45) NOT NULL,
  `Drame` VARCHAR(45) NOT NULL,
  `Horreur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codecategories`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infofilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infofilms` (
  `numerofilm` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `DateSortie` DATE NOT NULL,
  `Duree` TIME NOT NULL,
  `Realisateur` VARCHAR(45) NOT NULL,
  `infocategories_Codecategories` INT NOT NULL,
  PRIMARY KEY (`numerofilm`, `infocategories_Codecategories`),
  INDEX `fk_infofilms_infocategories1_idx` (`infocategories_Codecategories` ASC) VISIBLE,
  CONSTRAINT `fk_infofilms_infocategories1`
    FOREIGN KEY (`infocategories_Codecategories`)
    REFERENCES `clients`.`infocategories` (`Codecategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infoLocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infoLocation` (
  `datelocation` INT NOT NULL,
  `DateRetour` VARCHAR(45) NOT NULL,
  `Codeclient` INT NOT NULL,
  `numerofilm` INT NOT NULL,
  INDEX `Codeclient_idx` (`Codeclient` ASC) VISIBLE,
  INDEX `numerofilm_idx` (`numerofilm` ASC) VISIBLE,
  CONSTRAINT `Codeclient`
    FOREIGN KEY (`Codeclient`)
    REFERENCES `clients`.`infoclients` (`Codeclient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `numerofilm`
    FOREIGN KEY (`numerofilm`)
    REFERENCES `clients`.`infofilms` (`numerofilm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infopayements_has_infocategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infopayements_has_infocategories` (
  `infopayements_Codepayement` INT NOT NULL,
  `infocategories_Codecategories` INT NOT NULL,
  PRIMARY KEY (`infopayements_Codepayement`, `infocategories_Codecategories`),
  INDEX `fk_infopayements_has_infocategories_infocategories1_idx` (`infocategories_Codecategories` ASC) VISIBLE,
  INDEX `fk_infopayements_has_infocategories_infopayements1_idx` (`infopayements_Codepayement` ASC) VISIBLE,
  CONSTRAINT `fk_infopayements_has_infocategories_infopayements1`
    FOREIGN KEY (`infopayements_Codepayement`)
    REFERENCES `clients`.`infopayements` (`Codepayement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infopayements_has_infocategories_infocategories1`
    FOREIGN KEY (`infocategories_Codecategories`)
    REFERENCES `clients`.`infocategories` (`Codecategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `clients`.`infoclients_has_infofilms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients`.`infoclients_has_infofilms` (
  `infoclients_Codeclient` INT NOT NULL DEFAULT now,
  `infoclients_infopayements_Codepayement` INT NOT NULL,
  `infofilms_numerofilm` INT NOT NULL,
  `infofilms_infocategories_Codecategories` INT NOT NULL,
  `Datecreation` VARCHAR(45) NOT NULL DEFAULT 'now',
  `Dateretour` VARCHAR(45) NOT NULL DEFAULT 'now',
  PRIMARY KEY (`infoclients_Codeclient`, `infoclients_infopayements_Codepayement`, `infofilms_numerofilm`, `infofilms_infocategories_Codecategories`),
  INDEX `fk_infoclients_has_infofilms_infofilms1_idx` (`infofilms_numerofilm` ASC, `infofilms_infocategories_Codecategories` ASC) VISIBLE,
  INDEX `fk_infoclients_has_infofilms_infoclients1_idx` (`infoclients_Codeclient` ASC, `infoclients_infopayements_Codepayement` ASC) VISIBLE,
  CONSTRAINT `fk_infoclients_has_infofilms_infoclients1`
    FOREIGN KEY (`infoclients_Codeclient` , `infoclients_infopayements_Codepayement`)
    REFERENCES `clients`.`infoclients` (`Codeclient` , `infopayements_Codepayement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infoclients_has_infofilms_infofilms1`
    FOREIGN KEY (`infofilms_numerofilm` , `infofilms_infocategories_Codecategories`)
    REFERENCES `clients`.`infofilms` (`numerofilm` , `infocategories_Codecategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
